### ISSUE TITLE
Multi-arch build

### ISSUE THREAD

**Issue by ilteoood** [delfer/docker-alpine-ftp-server#10]
Hi,
Can you configure and release a Multi-architecture build? I would like to use this image on my raspberry pi. 
To do that, you can automate everything using the GitHub actions and a plugin that I did:
https://github.com/ilteoood/docker_buildx

Thank you so much, 
Matteo

**Comment by delfer** [comment]
@ilteoood can you make PR for this? I will be glad to merge it.

**Comment by ilteoood** [comment]
Hi,
sorry I've found another solution.

Matteo
