### ISSUE TITLE
Delete ftp users method is correct?

### ISSUE THREAD

**Issue by jesusmorenodiaz** [delfer/docker-alpine-ftp-server#13]
Is this correct? (using '/ftp/') instead of using just 'ftp'
#Remove all ftp users
grep '/ftp/' /etc/passwd | cut -d':' -f1 | xargs -n1 deluser

returns error and container stops
if you just replace '/ftp/' by 'ftp' works and delete "ftp" user
but triggers error...
deluser: can't find ftp in /etc/group
deluser: 'vsftp' still has 'ftp' as their primary group!

**Comment by jesusmorenodiaz** [comment]
Forgot this man! I made a mistake.

ftp server runs fine but with access to all folders!

Used my own script to generate on the fly your script "start_vsftpd.sh" from cat...<<EOF
and when running "start_vsftpd.sh" failed "ftp server" because it was generated corrupted.

**Comment by delfer** [comment]
@jesusmorenodiaz 
`grep '/ftp/' /etc/passwd | cut -d':' -f1 | xargs -n1 deluser`
Will find all users who has `/ftp/` in the path to their home folders.

I will close this issue.
