### ISSUE TITLE
docker-alpine-ftp-server delays the termination of my services

### ISSUE THREAD

**Issue by kugland** [delfer/docker-alpine-ftp-server#16]
When Docker tries to terminate my services, docker-alpine-ftp-server doesn't die when first asked to terminate, it only stops after Docker sends it a kill signal. One simple workaround is to add this line to the Dockerfile:

`STOPSIGNAL SIGKILL`

**Comment by delfer** [comment]
@kugland can you please make a PR?

**Comment by kugland** [comment]
@delfer, here it is: #25

**Comment by delfer** [comment]
https://github.com/delfer/docker-alpine-ftp-server/pull/25 merged
