### ISSUE TITLE
Can i use this server with sftp?

### ISSUE THREAD

**Issue by AdrianDumke** [delfer/docker-alpine-ftp-server#17]

**Comment by AdrianDumke** [comment]
I want to create a sftp connection. Is this possible?

**Comment by delfer** [comment]
This requires additional configuration what not in nearest plans.

**Comment by aminvakil** [comment]
@AdiDDumke123 See if https://github.com/aminvakil/docker-alpine-ftp-server-tls suits your needs, it's a fork of this repository.

**Comment by delfer** [comment]
@AdiDDumke123 SFTP (SSH File Transfer Protocol) - it's absolutely different protocol. You need SSH-server for SFTP, not FTP server.
FTPS (File Transfer Protocol + SSL) was implemented in https://github.com/delfer/docker-alpine-ftp-server/pull/40
@aminvakil thank you for you work and fork :)
