### ISSUE TITLE
Error 553 after last merge

### ISSUE THREAD

**Issue by raphaeldelio** [delfer/docker-alpine-ftp-server#23]
After last merge #22 I started getting error 553 when writing into the server:

Environment Variables: USERS=test|Abc123|/test/cf

Trying to write to /test/cf/file.zip

Error:
java.io.IOException: Failed to write to '/test/cf/file.zip'. Server replied with: 553 Could not create file.

I was also looking for the image with the previous version in Docker Hub and couldn't find it, only "latest" is available. Would it be possible to tag the versions as well? 

Thank you

**Comment by delfer** [comment]
Hello @raphaeldeli! Now I have no access to PC to amend last merge. Can you please make new PR to undo latest changes?

**Comment by delfer** [comment]
https://github.com/delfer/docker-alpine-ftp-server/pull/22 reverted

**Comment by raphaeldelio** [comment]
Thank you
