### ISSUE TITLE
Container is not starting

### ISSUE THREAD

**Issue by ankitkaushal** [delfer/docker-alpine-ftp-server#26]
Hi, 
I am getting the following logs and the container is not starting

Changing password for one
New password:
Bad password: too short
Retype password:
passwd: password for one changed by root

Thanks

**Comment by aminvakil** [comment]
Please share the command you're using to start the container completely.
If you're using a compose file, share that.

**Comment by ankitkaushal** [comment]
docker run \
    -p 21:21 \
    -p 21000-21010:21000-21010 \
    -e USERS="one|1234" \
    -e ADDRESS=ftp.site.domain \
    delfer/alpine-ftp-server

**Comment by aminvakil** [comment]
change `ftp.site.domain` to something which can be resolved to your ip

**Comment by JohnWalkerx** [comment]
Have you tried a longer password than `1234`?
Because it says it's too short.

**Comment by aminvakil** [comment]
even `-e ADDRESS=localhost` or `-e ADDRESS=1.2.3.4` where 1.2.3.4 is your IP works

**Comment by ankitkaushal** [comment]
I will try it and let you know.thanks for the help.

**Comment by ankitkaushal** [comment]
It works with changing ADDRESS to localhost. The message for password is only a warning

**Comment by aminvakil** [comment]
Try if it also works correctly connecting from your ftp client.

**Comment by ankitkaushal** [comment]
It works with a client as well, I see a file is getting uploaded. Thanks for the awsome library and quick support. The file is available at /ftp/one which can be seen in logs.
