### ISSUE TITLE
Passive port is not listening

### ISSUE THREAD

**Issue by ahmadsyahidr** [delfer/docker-alpine-ftp-server#28]
Somehow passive port is not listening inside the docker.

![image](https://user-images.githubusercontent.com/72850091/130176155-82248c56-fca8-43e3-bee1-f90951de384a.png)

**Comment by delfer** [comment]
The port will be opened after receiving the PASV command.
<img width="701" alt="image" src="https://user-images.githubusercontent.com/3233181/161105095-bf464220-ee83-4843-8370-deaa735721dd.png">

**Comment by delfer** [comment]
Not an issue
