### ISSUE TITLE
Ports not mapping, documentation beneficial.

### ISSUE THREAD

**Issue by michaelkrieger** [delfer/docker-alpine-ftp-server#29]
Just chased an unusual problem where Port 21 was not forwarding to the host, but accessing the docker 172.x.x.x image directly would answer back.

Turns out, the reason is I was using docker-compose and "When mapping ports in the HOST:CONTAINER format, you may experience erroneous results when using a container port lower than 60, because YAML parses numbers in the format xx:yy as a base-60 value. For this reason, we recommend always explicitly specifying your port mappings as strings."

While not a specific problem with this image, it may be wise to add a note or to show the port mapping in quotes in the example.

**Comment by delfer** [comment]
@michaelkrieger thank you very much! Can you please prepare the PR?

**Comment by delfer** [comment]
https://github.com/delfer/docker-alpine-ftp-server/pull/61 merged
