### ISSUE TITLE
`adduser: uid '82' in use`

### ISSUE THREAD

**Issue by 70599** [delfer/docker-alpine-ftp-server#31]
I set the UID to 82 in `USERS` variable, but the container outputs `adduser: uid '82' in use` and the user was not created.
I have set UID=82 in other containers(Nginx, PHP), so I prefer `82` to sharing the file permissions.

How can I know the UID `82` was taken by which user?
`grep '82' /etc/passwd` returns nothing.

If I do the following steps in the container, everything worked as except whthout any errors or warnings.

1. add user without define the UID
2. add `shadow` package
3. change the UID to 82 by `usermod` command

**Comment by delfer** [comment]
@70599 do you got this error on first start of created container or after restart?

**Comment by delfer** [comment]
It's not an user, it is the group)

```
/ # grep 82 /etc/group
www-data:x:82:
```

Fixed in https://github.com/delfer/docker-alpine-ftp-server/commit/9fd6e070ff6d49b3a0fb4c4009a3072e2f007291
