### ISSUE TITLE
ls command returns 500 Bad EPRT protocol. ftp: bind: Address already in use

### ISSUE THREAD

**Issue by MattAosta** [delfer/docker-alpine-ftp-server#32]
On the Ubuntu I've installed as Virtual Machine as soon as I login and I run `ls` i get this error:
```
500 Bad EPRT protocol.
ftp: bind: Address already in use
```
When I try to activate passive mode with `pass` and next i run `ls` I get this error:
```
522 Bad network protocol.
Passive mode refused.
```
<img width="167" alt="bug_docker_ftp" src="https://user-images.githubusercontent.com/88799463/158787090-f941d8aa-1f53-444c-9a90-6b1a922933ae.png">

**Comment by delfer** [comment]
@MattAosta it looks like you have some problem with port mapping or wrong ADDRESS variable value. Please prove full information about parameters of running docker container, IP addresses of both server and client and witch IP points DNS name in ADDRESS variable.
