### ISSUE TITLE
How to set local timezome?

### ISSUE THREAD

**Issue by Ingo-L** [delfer/docker-alpine-ftp-server#33]
Do anybody know to set the timezone for the ftp server? I have a time shift with all my clients of 1 hour. I think the server uses UTC.
I’d tried with TZ=Europe/Berlin, but not working. Thank you

**Comment by aminvakil** [comment]
Have you tried mounting `/etc/timezone` and `/etc/localtime`?

Something like this:
```
volumes:
  - "/etc/timezone:/etc/timezone:ro"
  - "/etc/localtime:/etc/localtime:ro"
```

**Comment by Ingo-L** [comment]
Thank you,

i linked  

- "/etc/localtime:/etc/localtime:ro" 

and additional i linked

- "/etc/vsftpd:/yourpath/vsftpd:ro"  

I made a copy of vsftpd.conf to /yourpath/vsftpd and added the entry in the file vsftpd.conf 

use_localtime=YES


that works for me :)
