### ISSUE TITLE
500 OOPS: invalid pasv_address

### ISSUE THREAD

**Issue by TrueOsiris** [delfer/docker-alpine-ftp-server#4]
I had to add this to /etc/vsftpd/vsftpd.conf
pasv_addr_resolve=YES

in order to avoid the "invalid pasv_address" disconnection when using filezilla

**Comment by delfer** [comment]
Commented in https://github.com/delfer/docker-alpine-ftp-server/pull/5

**Comment by delfer** [comment]
https://github.com/delfer/docker-alpine-ftp-server/pull/5 Merged
