### ISSUE TITLE
Remove TLSv1 Support

### ISSUE THREAD

**Issue by 53c70r** [delfer/docker-alpine-ftp-server#52]
Set -ossl_tlsv1=YES to -ossl_tlsv1=NO for security reasons.

0ec2032a4227 2023-03-15T10:05:40.417054Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
0ec2032a4227 2023-03-15T10:05:40.417055Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.

**Comment by delfer** [comment]
@53c70r hello! Thank you for this issue! Can you please make a PR for this update?

**Comment by 53c70r** [comment]
https://github.com/delfer/docker-alpine-ftp-server/pull/62

**Comment by delfer** [comment]
Merged https://github.com/delfer/docker-alpine-ftp-server/pull/62
