### ISSUE TITLE
no connection with letsencrypt cert

### ISSUE THREAD

**Issue by sm4rty-github** [delfer/docker-alpine-ftp-server#56]
I cant connect to the server when I have certs in the start command.

-e TLS_CERT="/storage/ssl/xxx.de.crt" -e TLS_KEY="/storage/ssl/xxx.de.key"

docker run -d --name vsftpd -p 21:21 -p 21000-21010:21000-21010 -e USERS="user|!password" -e ADDRESS=subdomain.xxx.de -e TLS_CERT="/storage/ssl/subdomain.xxx..de.crt" -e TLS_KEY="/storage/ssl/subdomain.xxx.de.key" -v "/var/media/fooBar/ftp:/ftp" user/branch-arm:vsftpd

```
docker logs -f vsftpd
Changing password for user
New password:
Retype password:
passwd: password for user changed by root
```

seems normal, but no connection.

when I use the same command without ssl, I can connect

**Comment by delfer** [comment]
Hello @sm4rty-github ! Which ftp client do you use? Can you share the error message from the client side?

**Comment by sm4rty-github** [comment]
I used ftpfs on linux to mount as a share but with filezilla its not working also from windows.

there is simply connection timed out, nothing more.

`wbQuad:~ # docker logs -f vsftpd
Changing password for user
New password:
Retype password:
passwd: password for user changed by root`

`Status:	Verbinde mit 192.168.177.54:21...
Status:	Verbindungsversuch fehlgeschlagen mit "ECONNREFUSED - Verbindung durch Server verweigert".
Fehler:	Herstellen der Verbindung zum Server fehlgeschlagen`

it seems it does not open a port when trying to run it with a cert file.

€dit: I forgot this line in the run command:
    -v "/etc/letsencrypt:/etc/letsencrypt:ro" 
so vsftpd couldnt even access the cert and key.

so now it is working with filezilla without problems.

**Comment by delfer** [comment]
problem solved
