### ISSUE TITLE
Error : Could not retrieve directory listing

### ISSUE THREAD

**Issue by derit** [delfer/docker-alpine-ftp-server#6]
hello, i found error 
```
Timeout detected. (data connection)
Could not retrieve directory listing
Error listing directory '/home/myUser'.
```

**Comment by delfer** [comment]
@derit can you share you configuration?

**Comment by derit** [comment]
docker run -d \
            -p 21:21 \
            -p 21000-21010:21000-21010 \
            -e USERS="one|1234567" \
            -e ADDRESS=ftp.site.domain \
            delfer/alpine-ftp-server

**Comment by delfer** [comment]
@derit I've checked this command, and It is working perfectly.
I just replace `ftp.site.domain` with my machine local IP (`192.168.1.1` for example) and can successful create/read/write files in the home folder `ftp://192.168.1.1/ftp/one/`
Can you share more information about your problem? How exactly are do start container? Where and how you access server? Where you found the error message?

**Comment by derit** [comment]
can i use a domain?  in case ```ftp.site.domain``` for my vps server?

**Comment by delfer** [comment]
Only IP at this moment. See https://github.com/delfer/docker-alpine-ftp-server/issues/4

**Comment by delfer** [comment]
Closed as inactive.
