### ISSUE TITLE
Change base image to 3.16.9

### ISSUE THREAD

**Issue by Razar911** [delfer/docker-alpine-ftp-server#66]
The OS Linux Alpine version 3.15.10 has been End-of-Life since 2023-11-01.
Please change base image in Dockerfile
ARG BASE_IMG=alpine:3.16.9

**Comment by delfer** [comment]
@Razar911 hello! Can you please prepare a Pull Request?

**Comment by Razar911** [comment]
sure, here is:
https://github.com/delfer/docker-alpine-ftp-server/pull/67

**Comment by delfer** [comment]
@Razar911 thank you very much! https://github.com/delfer/docker-alpine-ftp-server/pull/67 merged!
