### ISSUE TITLE
user passwords reset after container restart

### ISSUE THREAD

**Issue by andreworg** [delfer/docker-alpine-ftp-server#8]
Hi.
As an effect of adding them in the `start_vsftpd.sh` script, passwords from users defined in the USERS var get reset when stopping then restarting the container.
It could be avoided by checking if the user is already there before adding it.
I will fix it and try and submit a PR as soon as I find the time.

**Comment by delfer** [comment]
@andreworg thank for creating issue!
I understand what are you talking about, but I can not understand what real world problems can it create. Can you tell some use case?

**Comment by andreworg** [comment]
Let's say you create the container with a set of users and passwords you put in `USERS` and at a later time you need to change the password for some user. You don't want to destroy and recreate the container, because you have data/logs in it, maybe you made other runtime changes to the container, or maybe just because it's easier to run a shell and change the user's password with `passwd user`. Then you stop the container and start it back, for whatever reason, the simplest of which is you reboot the Docker daemon. All changed passwords are reset to the original value from `USERS`.

**Comment by andreworg** [comment]
On second thought, if one agrees user creation is to be done just once, it's probably better to put user creation into a separate script to be run at container creation in the Dockerfile, rather than at the entry point script.

**Comment by delfer** [comment]
This is not the way you should use Docker.
For example, couple days ago I updated container image. Changed entrypoint and Alpine version. You can not do the same inside created container, you should re-create container from new image and lose all of your settings made.
The same when you run your container in Kubernetes. Here you can not just restart container - only recreate (and some time on another node).
Any persistent data (like users and passwords) should be stored in persistent volume. But this is not the way for this project.
